routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

// Route::get('/', '')
Route::get('/', 'HomeController@index')->name('home');
Route::resource('Publications', 'PublicationController');
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
    Route::resource('users', 'UsersController');
});








// Route::get('/Publications/create', 'PublicationController@create')->name('publication.create');
// Route::post('/Publications', 'PublicationController@store')->name('publication.store');
// Route::delete('/Publications/{id}', 'PublicationController@destroy')->name('publication.destroy');

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
<div class="">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Liste des abonnés à la plateforme</div>

                <div class="card-body">
                    @if (count($users) > 0)
                    <table class="table table-striped">
                        <tr>
                            <th>#</th>
                            <th>Nom</th>
                            <th>Email</th>
                            <th>Actions</th>
                        </tr>
                        @foreach ($users as $user)
                        <tr class="sizing">
                            <td>{{$user->id}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td><a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-warning">Editer</a>
                                <a href="{{ route('admin.users.destroy', $user->id) }}" class="btn btn-danger">Delete</a></td>
                        </tr>
                        @endforeach
                    </table>
                @else
                <div class="alert alert-danger">Aucun autre abonné à part vous!</div>
                @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection