routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

// Route::get('/', '')
Route::get('/', 'HomeController@index')->name('home');
Route::resource('Publications', 'PublicationController');
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){
    Route::resource('users', 'UsersController');
});








// Route::get('/Publications/create', 'PublicationController@create')->name('publication.create');
// Route::post('/Publications', 'PublicationController@store')->name('publication.store');
// Route::delete('/Publications/{id}', 'PublicationController@destroy')->name('publication.destroy');

app/Publications.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Publications extends Model
{
    // Nom de la table
    // protected $table = 'publications';
    
    // Clé primaire
    // public $primaryKey = 'id';

    // /timestamps
    // public $timestamps = false;

    protected $dates = ['dateLimite'];


    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PublicationController.php
<?php

namespace App\Http\Controllers;

use App\Publications;
use Illuminate\Http\Request;

class PublicationController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $Publications = Publications::all();
        $Publications = Publications::orderBy('created_at', 'desc')->get();
        return view('publications.index')->with('publications', $Publications);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('publications.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'titre' => ['required', 'string'],
            'contenu' => ['required', 'string'],
            'dateLimite' => ['required', 'date'],
            'numeroCompte' => ['required', 'string'],
            'montant' => ['required', 'integer'],
            'image' => 'image|nullable|max:1999'
        ]);

        if($request->hasFile('image')){
            $filenameWithExt = $request->file('image')->getClientOriginalName();

            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $extension = $request->file('image')->getClientOriginalExtension();

            $fileNameToStore = $filename .'_'.time().'.'.$extension;

            $path = $request->file('image')->storeAs('public/images', $fileNameToStore);
        }
        else{
            $fileNameToStore = 'noimage.jpeg';
        }

        $Publication = new Publications;
        $Publication->titre = $request->input('titre');
        $Publication->contenu = $request->input('contenu');
        $Publication->dateLimite = $request->input('dateLimite');
        $Publication->numeroCompte = $request->input('numeroCompte');
        $Publication->montant = $request->input('montant');
        $Publication->image = $fileNameToStore;
        $Publication->user_id = auth()->user()->id;
        $Publication->save();

        return redirect('/')->with('success', 'Projet publié avec success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Publication = Publications::find($id);
        return view('publications.show')->with('publications', $Publication);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dd($id);
        $Publication = Publications::find($id);
        dd($id);
        $Publication->delete();

        return redirect('/Publications')->with('success', 'Suppression réussie!');
    }
}

resources/views/publications/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10 alert-info">
            <div class="card alert-info">
                <div class="card-header alert-warning">Publier un nouveau Projet</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('Publications.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group">
                            <label for="name">Titre du projet</label>
                                <input id="titre" type="text" class="form-control @error('titre') is-invalid @enderror" name="titre" value="{{ old('titre') }}"  autocomplete="titre" autofocus>

                                @error('titre')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="contenu">Contenu/Description du projet</label>
                                    <input id="contenu" type="textarea" class="form-control @error('contenu') is-invalid @enderror" name="contenu" value="{{ old('contenu') }}"  autocomplete="contenu" autofocus>
    
                                    @error('contenu')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="contenu">Date Limite du projet</label>
                                        <input id="dateLimite" type="date" class="form-control @error('dateLimite') is-invalid @enderror" name="dateLimite" value="{{ old('dateLimite') }}"  autocomplete="dateLimite" autofocus>
        
                                        @error('dateLimite')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="contenu">Numéro de Compte du Projet</label>
                                            <input id="numeroCompte" type="text" class="form-control @error('numeroCompte') is-invalid @enderror" name="numeroCompte" value="{{ old('numeroCompte') }}"  autocomplete="numeroCompte" autofocus>
            
                                            @error('numeroCompte')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="contenu">Montant du Projet</label>
                                                <input id="montant" type="number" maxlength="10" class="form-control @error('montant') is-invalid @enderror" name="montant" value="{{ old('montant') }}"  autocomplete="montant" autofocus>
                
                                                @error('montant')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                <div class="form-group">
                                    <div class="custom-file">
                                        <input type="file"  id="validatedCustomFile" name="image" class="custom-file-input
                                        @error('image') 
                                        is-invalid
                                        @enderror">
                                        <label for="validatedCustomFile" class="custom-file-label">Choisir image...</label>
                                        @error('image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary">
                                    Creer Projet
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/publications/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Projets en cours</h1>
    @if (count($publications) > 0)
    <a href="{{ route('Publications.create')}}" class="btn btn-info">Poster Projet</a>
    <hr>
    
    @foreach ($publications as $publication)
    <div class="card">
        {{-- <ul class="list-group list-group-flush"> --}}

        <div class="row">
            <div class="col-md-4">
                <img style="width: 100%" src="/storage/images/{{$publication->image}}" alt="" >
            </div>
            <div class="col-md-8 alert-info">
                <h2 class="px-5"><a href="/Publications/{{$publication->id}}">{{$publication->titre}}</a></h2>
                <hr>
                <h4 class="px-5 justify-content-right">Description: <small class="alert-success">{{$publication->contenu}}</small></h4>
                <hr>
                Publié le <small class="alert-warning"> {{$publication->created_at}}</small>
                <a href="/Publications/{{$publication->id}}" class="btn btn-danger" style="float: right; margin-right:2%;">Aperçue</a>
            </div>
            
        </div>
    {{-- </ul> --}}
    </div>
    <hr>
    <hr>
    @endforeach

    @else
        <div class="alert alert-danger">Aucune publication ajoutée</div>
    @endif
@endsection

resources/views/publications/show.blade.php
@extends('layouts.app')

@section('content')
<a href="/" class="btn btn-info">Retour</a>
    <h1>{{$publications->titre}}</h1>
    <div class="row">
        <div class="col-md-8 alert-info">
            <img style="width: 100%; height: 300px;" src="/storage/images/{{$publications->image}}" alt="" >
        </div>
        <div class="py-4 col-md-4">
            <h3>Informations Complémentaires</h3>
            <hr>
            <h5>Date limite pour le financement du projet: <small class="alert-danger">{{$publications->dateLimite->format('d/m/Y H:i')}}</small></h5>
            <hr>
            <h5>Numéro de compte du projet: <small class="alert-success">{{$publications->numeroCompte}}</small></h5>
            <hr>
            <h3>Montant du projet: <small class="alert-success">{{$publications->montant}}  FCFA</small></h3>
        </div>
    </div>
    <p>{{$publications->contenu}}</p>
    <hr>
    <small>Publié le {{$publications->created_at}}</small>
    {{-- <hr>
    <a href="#" class="btn btn-warning">Modifier</a>    <a href="{{ route('Publication.destroy', $publications->id)}}" class="btn btn-danger">Supprimer</a> --}}
@endsection